### ISSUE TITLE
Error: [apk-rebuild.sh:ERROR] keystore is missing

### ISSUE THREAD

**Issue by Scylla2020** [ilya-kozyr/android-ssl-pinning-bypass#1]
I get this error when I run `bash.exe apk-rebuild.sh "com.example.android_21.12.2-218_minAPI22.apk"` 

`[apk-rebuild.sh:ERROR] keystore is missing`

In the end it says the APK was processed successfully but on installing and testing through mitmproxy the app is still blocked. How do I get this working?

**Comment by ilya-kozyr** [comment]
Could you please post the entire script output?

**Comment by Scylla2020** [comment]
Sure

```
userx@DESKTOP-KB7C632:/mnt/c/Users/UserX/TestFolder$ bash.exe apk-rebuild.sh com.example.android_21.12.2-218_minAPI22.apk
[apk-rebuild.sh:ERROR] keystore is missing
[apk-rebuild.sh:INFO] Processing com.example.android_21.12.2-218_minAPI22.apk
[apk-rebuild.sh:INFO] Decompiling the apk file
I: Using Apktool 2.6.0 on com.example.android_21.12.2-218_minAPI22.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/userx/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
[apk-rebuild.sh:INFO] Processing @xml/network_security_config.xml
[apk-rebuild.sh:INFO] Checking AndroidManifest.xml
[apk-rebuild.sh:INFO] Building a new apk file
I: Using Apktool 2.6.0
I: Copying /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled classes.dex file...
I: Copying /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled classes2.dex file...
I: Copying /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled classes3.dex file...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
[apk-rebuild.sh:INFO] Signing the apk file
source:
        /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled/dist
zipalign location: BUILT_IN
        /tmp/uapksigner-5554474082708648992/linux-zipalign-29_0_21020186885716068964.tmp
keystore:
        [0] 161a0018 /tmp/temp_12784934397893903627_debug.keystore (DEBUG_EMBEDDED)

01. com.example.android_21.12.2-218_minAPI22.apk

        SIGN
        file: /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled/dist/com.example.android_21.12.2-218_minAPI22.apk (116.67 MiB)
        checksum: b82f3303afa5351850aae006d4ee96a84e30caf252a295c5905e744d6c054f32 (sha256)
        - zipalign success
        - sign success

        VERIFY
        file: /mnt/c/Users/UserX/TestFolder/com.example.android_21.12.2-218_minAPI22.apk-decompiled/dist/com.example.android_21.12.2-218_minAPI22.apk (117.23 MiB)
        checksum: d85527d034eb42d21417b6c528ecdb3e125d18baf8b390e73d83989b1732d325 (sha256)
        - zipalign verified
        - signature verified [v1, v2, v3]
                2 warnings
                Subject: CN=Android Debug, OU=Android, O=US, L=US, ST=US, C=US
                SHA256: 1e08a903aef9c3a721510b64ec764d01d3d094eb954161b62544ea8f187b5953 / SHA256withRSA
              
```
